languageCode = "en"
title = "Stanislav Myachenkov"
theme = "PaperMod"
baseURL = 'https://smyachenkov.com/'
googleAnalytics = "G-V263ZCTJXL"
enableRobotsTXT = true
enableEmoji = true
disqusShortname = "smyachenkov"
enableGitInfo = false
CommentAutoload = true

[params]
  featherIconsCDN = true
  mode = "auto"
  disableDisqusTypes = ["page"]

  ShowReadingTime = true
  ShowShareButtons = true
  # ShowToc = true
  # TocOpen = false
  # ShowBreadCrumbs = true
  ShowPostNavLinks = true

  [params.homeInfoParams]
  Title= "Not only coding"
  Content = "Notes about programming, career, and engineering culture."

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/stanislav-myachenkov/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/smyachenkov"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:s.myachenkov@gmail.com"

  [[params.socialIcons]]
  name = "telegram"
  url = "https://t.me/smyachenkov"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/s.myachenkov/"


[taxonomies]
  tag = "tags"

# Header Menu
[[menu.main]]
name = "Blog"
url = "/posts"
weight = 1

[[menu.main]]
name = "Singapore"
url = "/posts/this-is-singapore"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 5
