languageCode = "en"
title = "Stanislav Myachenkov"
theme = "PaperMod"
baseURL = 'https://smyachenkov.com/'
googleAnalytics = "G-V263ZCTJXL"
enableRobotsTXT = true
enableEmoji = true
disqusShortname = "smyachenkov"
enableGitInfo = false
CommentAutoload = true
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = []

[params]
  featherIconsCDN = true
  mode = "auto"
  disableDisqusTypes = ["page"]

  social = true

  ShowReadingTime = true
  ShowShareButtons = true
  # ShowToc = true
  # TocOpen = false
  # ShowBreadCrumbs = true

  # Disable prev and next buttons to avoid jumps between subblogs
  ShowPostNavLinks = false

  [params.homeInfoParams]
  Content = "Notes On Programming, Work, and Engineering Culture."

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/stanislav-myachenkov/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/smyachenkov"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:s.myachenkov@gmail.com"

  [[params.socialIcons]]
  name = "telegram"
  url = "https://t.me/smyachenkov"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/s.myachenkov/"


[taxonomies]
  tag = "tags"

# Header Menu
[[menu.main]]
name = "Blog"
url = "/posts"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 3
